#!/usr/bin/env python

from hashlib import shake_256
from base64 import b64encode
from getpass import getpass
from sys import stderr

def Hasher(msg="Hello, world!", length=32, encode='utf-8') -> str:
    H = shake_256(msg.encode(encode)).hexdigest(length)
    H = b64encode(H.encode(encode)).decode(encode)
    return str(H.replace('==', ''))

try:
    h = Hasher(f"{input('Enter your URL or app name: ')}<->{getpass('Enter your password(Hidden!): ')}//{input('Enter key salt: ')}", length=eval(input("Enter your length: ")))
    print(f"Your password: {h}")
except:
    print("Something went wrong! Please check your values and try again...", file=stderr)
